// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations.ImportationDb
{
    [DbContext(typeof(ImportationDbContext))]
    [Migration("20250214220332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Backend.Models.ImportationModels.AnonymatNom", b =>
                {
                    b.Property<string>("NumAnonymat")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("NumAnonymat");

                    b.HasIndex("Matricule");

                    b.ToTable("AnonymatsNoms");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.AnonymatNote", b =>
                {
                    b.Property<int>("IdAnonymatNote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEvaluation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumAnonymat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAnonymatNote");

                    b.HasIndex("IdEvaluation");

                    b.HasIndex("NumAnonymat");

                    b.ToTable("AnonymatsNotes");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeClasse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdFiliere")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdGrade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdNiveau")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSpecialite")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdClasse");

                    b.HasIndex("IdFiliere");

                    b.HasIndex("IdGrade");

                    b.HasIndex("IdNiveau");

                    b.HasIndex("IdSpecialite");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            IdClasse = 1,
                            CodeClasse = "ICT L1",
                            IdFiliere = 2,
                            IdGrade = 1,
                            IdNiveau = 1,
                            IdSpecialite = 1
                        },
                        new
                        {
                            IdClasse = 2,
                            CodeClasse = "ICT L2",
                            IdFiliere = 2,
                            IdGrade = 1,
                            IdNiveau = 2,
                            IdSpecialite = 1
                        },
                        new
                        {
                            IdClasse = 3,
                            CodeClasse = "ICT L2-GL",
                            IdFiliere = 2,
                            IdGrade = 1,
                            IdNiveau = 2,
                            IdSpecialite = 2
                        },
                        new
                        {
                            IdClasse = 4,
                            CodeClasse = "ICT L2-Secu",
                            IdFiliere = 2,
                            IdGrade = 1,
                            IdNiveau = 2,
                            IdSpecialite = 3
                        },
                        new
                        {
                            IdClasse = 5,
                            CodeClasse = "ICT L2-Reseau",
                            IdFiliere = 2,
                            IdGrade = 1,
                            IdNiveau = 2,
                            IdSpecialite = 4
                        },
                        new
                        {
                            IdClasse = 6,
                            CodeClasse = "ICT L3",
                            IdFiliere = 2,
                            IdGrade = 1,
                            IdNiveau = 2,
                            IdSpecialite = 1
                        });
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Etudiant", b =>
                {
                    b.Property<string>("Matricule")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenoms")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("VilleNaissance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Matricule");

                    b.ToTable("Etudiants");

                    b.HasData(
                        new
                        {
                            Matricule = "23U2292",
                            DateNaissance = new DateTime(2005, 10, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Djine",
                            Prenoms = "Sinto Pafing",
                            Sexe = "M",
                            VilleNaissance = "Moundou"
                        },
                        new
                        {
                            Matricule = "23U2293",
                            DateNaissance = new DateTime(2005, 10, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Alban",
                            Prenoms = "Kouyabe Pafing",
                            Sexe = "M",
                            VilleNaissance = "Moundou"
                        });
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Evaluation", b =>
                {
                    b.Property<int>("IdEvaluation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeEvaluation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Credit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUE")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdEvaluation");

                    b.HasIndex("IdUE");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Filiere", b =>
                {
                    b.Property<int>("IdFiliere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeFiliere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdFiliere");

                    b.ToTable("Filieres");

                    b.HasData(
                        new
                        {
                            IdFiliere = 1,
                            CodeFiliere = "INFO",
                            Intitule = "Informatique fondamental",
                            Title = "Fondamental Computer Science"
                        },
                        new
                        {
                            IdFiliere = 2,
                            CodeFiliere = "ICT4D",
                            Intitule = "Technologie de l'Information et de la Communication pour le Developpement",
                            Title = "Information and Communication Technology For Development"
                        },
                        new
                        {
                            IdFiliere = 3,
                            CodeFiliere = "MATHS",
                            Intitule = "Mathematiques",
                            Title = "Mathematics"
                        });
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Grade", b =>
                {
                    b.Property<int>("IdGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeGrade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("IdGrade");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            IdGrade = 1,
                            CodeGrade = "Licence"
                        },
                        new
                        {
                            IdGrade = 2,
                            CodeGrade = "Master"
                        },
                        new
                        {
                            IdGrade = 3,
                            CodeGrade = "Doctorat"
                        });
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Inscrit", b =>
                {
                    b.Property<int>("IdInscrit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Annee")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdClasse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdInscrit");

                    b.HasIndex("IdClasse");

                    b.HasIndex("Matricule");

                    b.ToTable("Inscrits");

                    b.HasData(
                        new
                        {
                            IdInscrit = 1,
                            Annee = "2024/2025",
                            IdClasse = 2,
                            Matricule = "23U2292"
                        },
                        new
                        {
                            IdInscrit = 2,
                            Annee = "2024/2025",
                            IdClasse = 1,
                            Matricule = "23U2293"
                        });
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Niveau", b =>
                {
                    b.Property<int>("IdNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeNiveau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("IdNiveau");

                    b.ToTable("Niveaux");

                    b.HasData(
                        new
                        {
                            IdNiveau = 1,
                            CodeNiveau = "L1"
                        },
                        new
                        {
                            IdNiveau = 2,
                            CodeNiveau = "L2"
                        },
                        new
                        {
                            IdNiveau = 3,
                            CodeNiveau = "L3"
                        },
                        new
                        {
                            IdNiveau = 4,
                            CodeNiveau = "M1"
                        },
                        new
                        {
                            IdNiveau = 5,
                            CodeNiveau = "M2"
                        },
                        new
                        {
                            IdNiveau = 6,
                            CodeNiveau = "D"
                        });
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.NoteCC", b =>
                {
                    b.Property<int>("IdNoteCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEvaluation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdNoteCC");

                    b.HasIndex("IdEvaluation");

                    b.HasIndex("Matricule");

                    b.ToTable("NotesCC");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.NoteTP", b =>
                {
                    b.Property<int>("IdNoteTP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEvaluation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdNoteTP");

                    b.HasIndex("IdEvaluation");

                    b.HasIndex("Matricule");

                    b.ToTable("NotesTP");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Programme", b =>
                {
                    b.Property<int>("IdProgramme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdClasse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Professeur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdProgramme");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdUE");

                    b.ToTable("Programmes");

                    b.HasData(
                        new
                        {
                            IdProgramme = 1,
                            IdClasse = 2,
                            IdUE = 1,
                            Professeur = "Djine"
                        },
                        new
                        {
                            IdProgramme = 2,
                            IdClasse = 2,
                            IdUE = 2,
                            Professeur = "Djine"
                        },
                        new
                        {
                            IdProgramme = 3,
                            IdClasse = 2,
                            IdUE = 3,
                            Professeur = "Djine"
                        },
                        new
                        {
                            IdProgramme = 4,
                            IdClasse = 2,
                            IdUE = 4,
                            Professeur = "Djine"
                        },
                        new
                        {
                            IdProgramme = 5,
                            IdClasse = 2,
                            IdUE = 5,
                            Professeur = "Djine"
                        });
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Specialite", b =>
                {
                    b.Property<int>("IdSpecialite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeSpecialite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdSpecialite");

                    b.ToTable("Specialites");

                    b.HasData(
                        new
                        {
                            IdSpecialite = 1,
                            CodeSpecialite = "None",
                            Intitule = "",
                            Title = ""
                        },
                        new
                        {
                            IdSpecialite = 2,
                            CodeSpecialite = "GL",
                            Intitule = "Genie Logiciel",
                            Title = "Sotfware Engeneering"
                        },
                        new
                        {
                            IdSpecialite = 3,
                            CodeSpecialite = "Secu",
                            Intitule = "Cyber Securite",
                            Title = "Cyber Security"
                        },
                        new
                        {
                            IdSpecialite = 4,
                            CodeSpecialite = "Reseau",
                            Intitule = "Reseau Informatique",
                            Title = "Computer Networking"
                        });
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.UE", b =>
                {
                    b.Property<int>("IdUE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeUE")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUE");

                    b.ToTable("UEs");

                    b.HasData(
                        new
                        {
                            IdUE = 1,
                            CodeUE = "ICT201",
                            Intitule = "",
                            Semestre = "S1",
                            Title = ""
                        },
                        new
                        {
                            IdUE = 2,
                            CodeUE = "ICT203",
                            Intitule = "",
                            Semestre = "S1",
                            Title = ""
                        },
                        new
                        {
                            IdUE = 3,
                            CodeUE = "ICT205",
                            Intitule = "",
                            Semestre = "S1",
                            Title = ""
                        },
                        new
                        {
                            IdUE = 4,
                            CodeUE = "ICT207",
                            Intitule = "",
                            Semestre = "S1",
                            Title = ""
                        },
                        new
                        {
                            IdUE = 5,
                            CodeUE = "ICT202",
                            Intitule = "",
                            Semestre = "S2",
                            Title = ""
                        });
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.AnonymatNom", b =>
                {
                    b.HasOne("Backend.Models.ImportationModels.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("Matricule")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.AnonymatNote", b =>
                {
                    b.HasOne("Backend.Models.ImportationModels.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("IdEvaluation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ImportationModels.AnonymatNom", "AnonymatNom")
                        .WithMany()
                        .HasForeignKey("NumAnonymat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnonymatNom");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Classe", b =>
                {
                    b.HasOne("Backend.Models.ImportationModels.Filiere", "Filiere")
                        .WithMany()
                        .HasForeignKey("IdFiliere")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.ImportationModels.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("IdGrade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.ImportationModels.Niveau", "Niveau")
                        .WithMany()
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.ImportationModels.Specialite", "Specialite")
                        .WithMany()
                        .HasForeignKey("IdSpecialite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filiere");

                    b.Navigation("Grade");

                    b.Navigation("Niveau");

                    b.Navigation("Specialite");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Evaluation", b =>
                {
                    b.HasOne("Backend.Models.ImportationModels.UE", "UE")
                        .WithMany()
                        .HasForeignKey("IdUE")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UE");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Inscrit", b =>
                {
                    b.HasOne("Backend.Models.ImportationModels.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.ImportationModels.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("Matricule")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.NoteCC", b =>
                {
                    b.HasOne("Backend.Models.ImportationModels.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("IdEvaluation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.ImportationModels.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("Matricule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.NoteTP", b =>
                {
                    b.HasOne("Backend.Models.ImportationModels.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("IdEvaluation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.ImportationModels.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("Matricule")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Backend.Models.ImportationModels.Programme", b =>
                {
                    b.HasOne("Backend.Models.ImportationModels.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.ImportationModels.UE", "UE")
                        .WithMany()
                        .HasForeignKey("IdUE")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("UE");
                });
#pragma warning restore 612, 618
        }
    }
}
